name: Mypy

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install mypy
    - name: Analysing the code with mypy
      run: |
        python -m mypy --install-types --non-interactive .
    - name: Discord notification
      continue-on-error: true
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '<@886055326107971636> just got updated ({{ EVENT_PAYLOAD.push.compare }}) ... Yo someone in <@&889831216646352956>, restart the docker container pls....'
